name: Unit tests

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: golang:1.24

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run unit tests
        run: go test -v ./...